version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - 9998:9998
    depends_on:
      - postgres
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    stdin_open: true
    tty: true
    ports:
      - 5432:5432